DROP TABLE IF EXISTS follow CASCADE;
CREATE TABLE follow (
    ID SERIAL,
    FOLLOWER_ID INT,
    FOLLOWEE_ID INT,
    FOREIGN KEY (FOLLOWER_ID) REFERENCES user_account(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWEE_ID) REFERENCES user_account(ID) ON DELETE CASCADE,
    PRIMARY KEY (ID)
);