DROP TABLE IF EXISTS follow CASCADE;
CREATE TABLE follow (
        ID SERIAL,
        FOLLOWER_ID INT NOT NULL,
        FOLLOWEE_ID INT NOT NULL,
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        FOREIGN KEY (FOLLOWER_ID) REFERENCES user_account(ID) ON DELETE CASCADE,
        FOREIGN KEY (FOLLOWEE_ID) REFERENCES user_account(ID) ON DELETE CASCADE,
        PRIMARY KEY (ID)
);
