DROP TABLE IF EXISTS post CASCADE;
CREATE TABLE post (
    ID SERIAL,
    TITLE VARCHAR(256) NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    WRITER_ID INT NOT NULL,
    FOREIGN KEY (WRITER_ID) REFERENCES user_account(ID),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID)
)